 
version: '3.8'
 
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: coil1234
      MYSQL_DATABASE: coil_db
      MYSQL_USER: coil
      MYSQL_PASSWORD: coil1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
 
volumes:
  mysql_data: